// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service_test

import (
	"context"
	"github.com/sgaunet/template-api/pkg/authors/repository"
	"sync"
)

// Ensure, that QuerierMock does implement repository.Querier.
// If this is not the case, regenerate this file with moq.
var _ repository.Querier = &QuerierMock{}

// QuerierMock is a mock implementation of repository.Querier.
//
//	func TestSomethingThatUsesQuerier(t *testing.T) {
//
//		// make and configure a mocked repository.Querier
//		mockedQuerier := &QuerierMock{
//			CreateAuthorFunc: func(ctx context.Context, arg repository.CreateAuthorParams) (repository.Author, error) {
//				panic("mock out the CreateAuthor method")
//			},
//			DeleteAuthorFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the DeleteAuthor method")
//			},
//			GetAuthorFunc: func(ctx context.Context, id int64) (repository.Author, error) {
//				panic("mock out the GetAuthor method")
//			},
//			ListAuthorsFunc: func(ctx context.Context) ([]repository.Author, error) {
//				panic("mock out the ListAuthors method")
//			},
//			PartialUpdateAuthorFunc: func(ctx context.Context, arg repository.PartialUpdateAuthorParams) (repository.Author, error) {
//				panic("mock out the PartialUpdateAuthor method")
//			},
//			UpdateAuthorFunc: func(ctx context.Context, arg repository.UpdateAuthorParams) (repository.Author, error) {
//				panic("mock out the UpdateAuthor method")
//			},
//		}
//
//		// use mockedQuerier in code that requires repository.Querier
//		// and then make assertions.
//
//	}
type QuerierMock struct {
	// CreateAuthorFunc mocks the CreateAuthor method.
	CreateAuthorFunc func(ctx context.Context, arg repository.CreateAuthorParams) (repository.Author, error)

	// DeleteAuthorFunc mocks the DeleteAuthor method.
	DeleteAuthorFunc func(ctx context.Context, id int64) error

	// GetAuthorFunc mocks the GetAuthor method.
	GetAuthorFunc func(ctx context.Context, id int64) (repository.Author, error)

	// ListAuthorsFunc mocks the ListAuthors method.
	ListAuthorsFunc func(ctx context.Context) ([]repository.Author, error)

	// PartialUpdateAuthorFunc mocks the PartialUpdateAuthor method.
	PartialUpdateAuthorFunc func(ctx context.Context, arg repository.PartialUpdateAuthorParams) (repository.Author, error)

	// UpdateAuthorFunc mocks the UpdateAuthor method.
	UpdateAuthorFunc func(ctx context.Context, arg repository.UpdateAuthorParams) (repository.Author, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateAuthor holds details about calls to the CreateAuthor method.
		CreateAuthor []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg repository.CreateAuthorParams
		}
		// DeleteAuthor holds details about calls to the DeleteAuthor method.
		DeleteAuthor []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// GetAuthor holds details about calls to the GetAuthor method.
		GetAuthor []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// ListAuthors holds details about calls to the ListAuthors method.
		ListAuthors []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// PartialUpdateAuthor holds details about calls to the PartialUpdateAuthor method.
		PartialUpdateAuthor []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg repository.PartialUpdateAuthorParams
		}
		// UpdateAuthor holds details about calls to the UpdateAuthor method.
		UpdateAuthor []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg repository.UpdateAuthorParams
		}
	}
	lockCreateAuthor        sync.RWMutex
	lockDeleteAuthor        sync.RWMutex
	lockGetAuthor           sync.RWMutex
	lockListAuthors         sync.RWMutex
	lockPartialUpdateAuthor sync.RWMutex
	lockUpdateAuthor        sync.RWMutex
}

// CreateAuthor calls CreateAuthorFunc.
func (mock *QuerierMock) CreateAuthor(ctx context.Context, arg repository.CreateAuthorParams) (repository.Author, error) {
	if mock.CreateAuthorFunc == nil {
		panic("QuerierMock.CreateAuthorFunc: method is nil but Querier.CreateAuthor was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg repository.CreateAuthorParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockCreateAuthor.Lock()
	mock.calls.CreateAuthor = append(mock.calls.CreateAuthor, callInfo)
	mock.lockCreateAuthor.Unlock()
	return mock.CreateAuthorFunc(ctx, arg)
}

// CreateAuthorCalls gets all the calls that were made to CreateAuthor.
// Check the length with:
//
//	len(mockedQuerier.CreateAuthorCalls())
func (mock *QuerierMock) CreateAuthorCalls() []struct {
	Ctx context.Context
	Arg repository.CreateAuthorParams
} {
	var calls []struct {
		Ctx context.Context
		Arg repository.CreateAuthorParams
	}
	mock.lockCreateAuthor.RLock()
	calls = mock.calls.CreateAuthor
	mock.lockCreateAuthor.RUnlock()
	return calls
}

// DeleteAuthor calls DeleteAuthorFunc.
func (mock *QuerierMock) DeleteAuthor(ctx context.Context, id int64) error {
	if mock.DeleteAuthorFunc == nil {
		panic("QuerierMock.DeleteAuthorFunc: method is nil but Querier.DeleteAuthor was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDeleteAuthor.Lock()
	mock.calls.DeleteAuthor = append(mock.calls.DeleteAuthor, callInfo)
	mock.lockDeleteAuthor.Unlock()
	return mock.DeleteAuthorFunc(ctx, id)
}

// DeleteAuthorCalls gets all the calls that were made to DeleteAuthor.
// Check the length with:
//
//	len(mockedQuerier.DeleteAuthorCalls())
func (mock *QuerierMock) DeleteAuthorCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockDeleteAuthor.RLock()
	calls = mock.calls.DeleteAuthor
	mock.lockDeleteAuthor.RUnlock()
	return calls
}

// GetAuthor calls GetAuthorFunc.
func (mock *QuerierMock) GetAuthor(ctx context.Context, id int64) (repository.Author, error) {
	if mock.GetAuthorFunc == nil {
		panic("QuerierMock.GetAuthorFunc: method is nil but Querier.GetAuthor was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetAuthor.Lock()
	mock.calls.GetAuthor = append(mock.calls.GetAuthor, callInfo)
	mock.lockGetAuthor.Unlock()
	return mock.GetAuthorFunc(ctx, id)
}

// GetAuthorCalls gets all the calls that were made to GetAuthor.
// Check the length with:
//
//	len(mockedQuerier.GetAuthorCalls())
func (mock *QuerierMock) GetAuthorCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockGetAuthor.RLock()
	calls = mock.calls.GetAuthor
	mock.lockGetAuthor.RUnlock()
	return calls
}

// ListAuthors calls ListAuthorsFunc.
func (mock *QuerierMock) ListAuthors(ctx context.Context) ([]repository.Author, error) {
	if mock.ListAuthorsFunc == nil {
		panic("QuerierMock.ListAuthorsFunc: method is nil but Querier.ListAuthors was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListAuthors.Lock()
	mock.calls.ListAuthors = append(mock.calls.ListAuthors, callInfo)
	mock.lockListAuthors.Unlock()
	return mock.ListAuthorsFunc(ctx)
}

// ListAuthorsCalls gets all the calls that were made to ListAuthors.
// Check the length with:
//
//	len(mockedQuerier.ListAuthorsCalls())
func (mock *QuerierMock) ListAuthorsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListAuthors.RLock()
	calls = mock.calls.ListAuthors
	mock.lockListAuthors.RUnlock()
	return calls
}

// PartialUpdateAuthor calls PartialUpdateAuthorFunc.
func (mock *QuerierMock) PartialUpdateAuthor(ctx context.Context, arg repository.PartialUpdateAuthorParams) (repository.Author, error) {
	if mock.PartialUpdateAuthorFunc == nil {
		panic("QuerierMock.PartialUpdateAuthorFunc: method is nil but Querier.PartialUpdateAuthor was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg repository.PartialUpdateAuthorParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockPartialUpdateAuthor.Lock()
	mock.calls.PartialUpdateAuthor = append(mock.calls.PartialUpdateAuthor, callInfo)
	mock.lockPartialUpdateAuthor.Unlock()
	return mock.PartialUpdateAuthorFunc(ctx, arg)
}

// PartialUpdateAuthorCalls gets all the calls that were made to PartialUpdateAuthor.
// Check the length with:
//
//	len(mockedQuerier.PartialUpdateAuthorCalls())
func (mock *QuerierMock) PartialUpdateAuthorCalls() []struct {
	Ctx context.Context
	Arg repository.PartialUpdateAuthorParams
} {
	var calls []struct {
		Ctx context.Context
		Arg repository.PartialUpdateAuthorParams
	}
	mock.lockPartialUpdateAuthor.RLock()
	calls = mock.calls.PartialUpdateAuthor
	mock.lockPartialUpdateAuthor.RUnlock()
	return calls
}

// UpdateAuthor calls UpdateAuthorFunc.
func (mock *QuerierMock) UpdateAuthor(ctx context.Context, arg repository.UpdateAuthorParams) (repository.Author, error) {
	if mock.UpdateAuthorFunc == nil {
		panic("QuerierMock.UpdateAuthorFunc: method is nil but Querier.UpdateAuthor was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg repository.UpdateAuthorParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockUpdateAuthor.Lock()
	mock.calls.UpdateAuthor = append(mock.calls.UpdateAuthor, callInfo)
	mock.lockUpdateAuthor.Unlock()
	return mock.UpdateAuthorFunc(ctx, arg)
}

// UpdateAuthorCalls gets all the calls that were made to UpdateAuthor.
// Check the length with:
//
//	len(mockedQuerier.UpdateAuthorCalls())
func (mock *QuerierMock) UpdateAuthorCalls() []struct {
	Ctx context.Context
	Arg repository.UpdateAuthorParams
} {
	var calls []struct {
		Ctx context.Context
		Arg repository.UpdateAuthorParams
	}
	mock.lockUpdateAuthor.RLock()
	calls = mock.calls.UpdateAuthor
	mock.lockUpdateAuthor.RUnlock()
	return calls
}
