// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service_test

import (
	"context"
	"github.com/sgaunet/template-api/pkg/books/repository"
	"sync"
)

// Ensure, that QuerierMock does implement repository.Querier.
// If this is not the case, regenerate this file with moq.
var _ repository.Querier = &QuerierMock{}

// QuerierMock is a mock implementation of repository.Querier.
//
//	func TestSomethingThatUsesQuerier(t *testing.T) {
//
//		// make and configure a mocked repository.Querier
//		mockedQuerier := &QuerierMock{
//			CreateBookFunc: func(ctx context.Context, arg repository.CreateBookParams) (repository.Book, error) {
//				panic("mock out the CreateBook method")
//			},
//			DeleteBookFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the DeleteBook method")
//			},
//			GetBookFunc: func(ctx context.Context, id int64) (repository.Book, error) {
//				panic("mock out the GetBook method")
//			},
//			ListBooksFunc: func(ctx context.Context) ([]repository.Book, error) {
//				panic("mock out the ListBooks method")
//			},
//			UpdateTitleBookFunc: func(ctx context.Context, arg repository.UpdateTitleBookParams) (repository.Book, error) {
//				panic("mock out the UpdateTitleBook method")
//			},
//		}
//
//		// use mockedQuerier in code that requires repository.Querier
//		// and then make assertions.
//
//	}
type QuerierMock struct {
	// CreateBookFunc mocks the CreateBook method.
	CreateBookFunc func(ctx context.Context, arg repository.CreateBookParams) (repository.Book, error)

	// DeleteBookFunc mocks the DeleteBook method.
	DeleteBookFunc func(ctx context.Context, id int64) error

	// GetBookFunc mocks the GetBook method.
	GetBookFunc func(ctx context.Context, id int64) (repository.Book, error)

	// ListBooksFunc mocks the ListBooks method.
	ListBooksFunc func(ctx context.Context) ([]repository.Book, error)

	// UpdateTitleBookFunc mocks the UpdateTitleBook method.
	UpdateTitleBookFunc func(ctx context.Context, arg repository.UpdateTitleBookParams) (repository.Book, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateBook holds details about calls to the CreateBook method.
		CreateBook []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg repository.CreateBookParams
		}
		// DeleteBook holds details about calls to the DeleteBook method.
		DeleteBook []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// GetBook holds details about calls to the GetBook method.
		GetBook []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// ListBooks holds details about calls to the ListBooks method.
		ListBooks []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// UpdateTitleBook holds details about calls to the UpdateTitleBook method.
		UpdateTitleBook []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg repository.UpdateTitleBookParams
		}
	}
	lockCreateBook      sync.RWMutex
	lockDeleteBook      sync.RWMutex
	lockGetBook         sync.RWMutex
	lockListBooks       sync.RWMutex
	lockUpdateTitleBook sync.RWMutex
}

// CreateBook calls CreateBookFunc.
func (mock *QuerierMock) CreateBook(ctx context.Context, arg repository.CreateBookParams) (repository.Book, error) {
	if mock.CreateBookFunc == nil {
		panic("QuerierMock.CreateBookFunc: method is nil but Querier.CreateBook was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg repository.CreateBookParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockCreateBook.Lock()
	mock.calls.CreateBook = append(mock.calls.CreateBook, callInfo)
	mock.lockCreateBook.Unlock()
	return mock.CreateBookFunc(ctx, arg)
}

// CreateBookCalls gets all the calls that were made to CreateBook.
// Check the length with:
//
//	len(mockedQuerier.CreateBookCalls())
func (mock *QuerierMock) CreateBookCalls() []struct {
	Ctx context.Context
	Arg repository.CreateBookParams
} {
	var calls []struct {
		Ctx context.Context
		Arg repository.CreateBookParams
	}
	mock.lockCreateBook.RLock()
	calls = mock.calls.CreateBook
	mock.lockCreateBook.RUnlock()
	return calls
}

// DeleteBook calls DeleteBookFunc.
func (mock *QuerierMock) DeleteBook(ctx context.Context, id int64) error {
	if mock.DeleteBookFunc == nil {
		panic("QuerierMock.DeleteBookFunc: method is nil but Querier.DeleteBook was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDeleteBook.Lock()
	mock.calls.DeleteBook = append(mock.calls.DeleteBook, callInfo)
	mock.lockDeleteBook.Unlock()
	return mock.DeleteBookFunc(ctx, id)
}

// DeleteBookCalls gets all the calls that were made to DeleteBook.
// Check the length with:
//
//	len(mockedQuerier.DeleteBookCalls())
func (mock *QuerierMock) DeleteBookCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockDeleteBook.RLock()
	calls = mock.calls.DeleteBook
	mock.lockDeleteBook.RUnlock()
	return calls
}

// GetBook calls GetBookFunc.
func (mock *QuerierMock) GetBook(ctx context.Context, id int64) (repository.Book, error) {
	if mock.GetBookFunc == nil {
		panic("QuerierMock.GetBookFunc: method is nil but Querier.GetBook was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetBook.Lock()
	mock.calls.GetBook = append(mock.calls.GetBook, callInfo)
	mock.lockGetBook.Unlock()
	return mock.GetBookFunc(ctx, id)
}

// GetBookCalls gets all the calls that were made to GetBook.
// Check the length with:
//
//	len(mockedQuerier.GetBookCalls())
func (mock *QuerierMock) GetBookCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockGetBook.RLock()
	calls = mock.calls.GetBook
	mock.lockGetBook.RUnlock()
	return calls
}

// ListBooks calls ListBooksFunc.
func (mock *QuerierMock) ListBooks(ctx context.Context) ([]repository.Book, error) {
	if mock.ListBooksFunc == nil {
		panic("QuerierMock.ListBooksFunc: method is nil but Querier.ListBooks was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListBooks.Lock()
	mock.calls.ListBooks = append(mock.calls.ListBooks, callInfo)
	mock.lockListBooks.Unlock()
	return mock.ListBooksFunc(ctx)
}

// ListBooksCalls gets all the calls that were made to ListBooks.
// Check the length with:
//
//	len(mockedQuerier.ListBooksCalls())
func (mock *QuerierMock) ListBooksCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListBooks.RLock()
	calls = mock.calls.ListBooks
	mock.lockListBooks.RUnlock()
	return calls
}

// UpdateTitleBook calls UpdateTitleBookFunc.
func (mock *QuerierMock) UpdateTitleBook(ctx context.Context, arg repository.UpdateTitleBookParams) (repository.Book, error) {
	if mock.UpdateTitleBookFunc == nil {
		panic("QuerierMock.UpdateTitleBookFunc: method is nil but Querier.UpdateTitleBook was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg repository.UpdateTitleBookParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockUpdateTitleBook.Lock()
	mock.calls.UpdateTitleBook = append(mock.calls.UpdateTitleBook, callInfo)
	mock.lockUpdateTitleBook.Unlock()
	return mock.UpdateTitleBookFunc(ctx, arg)
}

// UpdateTitleBookCalls gets all the calls that were made to UpdateTitleBook.
// Check the length with:
//
//	len(mockedQuerier.UpdateTitleBookCalls())
func (mock *QuerierMock) UpdateTitleBookCalls() []struct {
	Ctx context.Context
	Arg repository.UpdateTitleBookParams
} {
	var calls []struct {
		Ctx context.Context
		Arg repository.UpdateTitleBookParams
	}
	mock.lockUpdateTitleBook.RLock()
	calls = mock.calls.UpdateTitleBook
	mock.lockUpdateTitleBook.RUnlock()
	return calls
}
