// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: queries-books.sql

package repository

import (
	"context"
)

const createBook = `-- name: CreateBook :one
INSERT INTO books (title, author_id)
VALUES ($1, $2)
RETURNING id, title, author_id
`

type CreateBookParams struct {
	Title    string `db:"title" json:"title"`
	AuthorID int64  `db:"author_id" json:"author_id"`
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, createBook, arg.Title, arg.AuthorID)
	var i Book
	err := row.Scan(&i.ID, &i.Title, &i.AuthorID)
	return i, err
}

const deleteBook = `-- name: DeleteBook :exec
DELETE
FROM books
WHERE id = $1
`

func (q *Queries) DeleteBook(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBook, id)
	return err
}

const getBook = `-- name: GetBook :one
SELECT id, title, author_id
FROM books
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetBook(ctx context.Context, id int64) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBook, id)
	var i Book
	err := row.Scan(&i.ID, &i.Title, &i.AuthorID)
	return i, err
}

const listBooks = `-- name: ListBooks :many
SELECT id, title, author_id
FROM books
ORDER BY title
`

func (q *Queries) ListBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, listBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Book{}
	for rows.Next() {
		var i Book
		if err := rows.Scan(&i.ID, &i.Title, &i.AuthorID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTitleBook = `-- name: UpdateTitleBook :one
UPDATE books
SET title = $2
WHERE id = $1
RETURNING id, title, author_id
`

type UpdateTitleBookParams struct {
	ID    int64  `db:"id" json:"id"`
	Title string `db:"title" json:"title"`
}

func (q *Queries) UpdateTitleBook(ctx context.Context, arg UpdateTitleBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, updateTitleBook, arg.ID, arg.Title)
	var i Book
	err := row.Scan(&i.ID, &i.Title, &i.AuthorID)
	return i, err
}
